### ISSUE TITLE
Some kinda version issue 

### ISSUE THREAD

**Issue by AlabhyaVaibhav** [pranjal4697/FPLAssist#4]
urllib.request is available only in Py3, let me see a work around. Mentions the errors you are facing the comments, will look into them. 

This is for the new code you uploaded

**Comment by pranjalnaman** [comment]
This is not urllib.request that we are using
requests is a different module
I'm using python 3
still can't seem to get around

**Comment by pranjalnaman** [comment]
c:\Program Files\Sublime Text 3>fpldatascraper.py
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\fpldatascraper.py", line 8, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by AlabhyaVaibhav** [comment]
https://stackoverflow.com/questions/17309288/importerror-no-module-named-requests 

^ check this out

**Comment by pranjalnaman** [comment]
fixed all the bugs. scraper code is ready. closing issue.
